-- Create Announcements table
create table public.announcements (
  id bigint generated by default as identity primary key,
  message text not null,
  link text,
  link_text text,
  is_active boolean default false,
  background_color text default '#332b00', -- Darkish gold/brown from screenshot
  text_color text default '#f5a623', -- Orange/Gold
  icon text default 'alert', -- alert, info
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- RLS
alter table public.announcements enable row level security;

-- Everyone can view active announcements
create policy "Anyone can view active announcements." 
  on public.announcements for select 
  using ( is_active = true or exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' ) );

-- Only admins can insert/update/delete
create policy "Admins can manage announcements." 
  on public.announcements for all 
  using ( exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' ) );
