-- 1. USERS (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text not null,
  full_name text,
  avatar_url text,
  role text default 'member' check (role in ('admin', 'member')),
  job_title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. SEMESTERS (For Performance Reviews)
create table public.semesters (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g., "Semester 1 2026"
  start_date date not null,
  end_date date not null,
  is_active boolean default false
);

-- 3. KPIS (Key Performance Indicators)
create table public.kpis (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  semester_id bigint references public.semesters(id) not null,
  description text not null,
  target_metric text, -- e.g., "Complete 50 design tickets"
  created_at timestamp with time zone default now()
);

-- 4. PROJECTS
create table public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  color_code text default '#000000', -- Hex code for UI tags
  icon text default 'folder',
  status text default 'active' check (status in ('active', 'archived')),
  created_by uuid references public.profiles(id)
);

-- 5. TASKS (The Core Table)
create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  project_id bigint references public.projects(id) not null, -- MANDATORY: No orphans
  assignee_id uuid references public.profiles(id) not null,
  
  -- MANDATORY DATES for Gantt
  start_date timestamp with time zone not null, 
  end_date timestamp with time zone not null,
  
  status text default 'todo' check (status in ('todo', 'in_progress', 'done')),
  
  -- EVIDENCE & CLOSING
  evidence_link text, -- Required by UI logic if status -> done
  remarks text,
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- RLS POLICIES
alter table public.profiles enable row level security;
alter table public.semesters enable row level security;
alter table public.kpis enable row level security;
alter table public.projects enable row level security;
alter table public.tasks enable row level security;

-- Profiles: Publicly readable (authenticated), editable only by self or Admin.
create policy "Public profiles are viewable by everyone." on public.profiles for select using ( true );
create policy "Users can update own profile." on public.profiles for update using ( auth.uid() = id );

-- Projects: Readable by all authenticated users (Open Organization).
create policy "Projects are viewable by everyone." on public.projects for select using ( true );
create policy "Admins can create projects." on public.projects for insert with check ( 
  exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' )
);

-- Tasks: Readable by all. Editable by Assignee or Admin.
create policy "Tasks are viewable by everyone." on public.tasks for select using ( true );
create policy "Assignees look update tasks." on public.tasks for update using ( 
  auth.uid() = assignee_id or 
  exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' )
);

-- KPIs: Readable by Owner and Admin only.
create policy "Users view own KPIs." on public.kpis for select using ( auth.uid() = user_id );
